### ISSUE TITLE
Min fingerprint size for one second of audio data?

### ISSUE THREAD

**Issue by CyberSinh** [acoustid/chromaprint#45]
Hi Lukas,

I understand that the maximum size in bytes of a one-second footprint of audio data is 32 (`8 * sizeof(uint)`). So, I can easily calculate the size in bytes for a buffer that may contain the whole fingerprint.

But, when I request a fingerprint for the first 120 seconds of an audio file, its size is 3792 bytes (`uint[948]`) and not 3840 (120x8x4). If I request a fingerprint for the first 60 seconds, its size is 1852 bytes (`uint[462]`) and not 1920 (60x8x4).

How can I calculate the **minimum** size in bytes that the fingerprint should have based on a given duration?

Thank you.

**Comment by CyberSinh** [comment]
I have the impression that the expected size can be reduced up to 84 bytes (for smaller fingerprints). 
Is there an explanation?

**Comment by lalinsky** [comment]
Are we talking about the raw fingerprints (i.e. arrays of integers) or the compressed ones?

The raw fingerprints are fixed. The number of 32-bit integers is going to be `(duration_in_seconds * 11025 - 4096) / 1365 - 15 - 4 + 1`. It can be off +/-1 due to rounding.

The compressed ones have no minimum or maximum size. The algorithm is rather involved and I'd rather not make the estimate. I'd suggest you make 120 seconds of silence and fingerprint that. That should get you the smallest possible compressed fingerprint.

**Comment by CyberSinh** [comment]
Thank you Lukas. 
I talked about the raw fingerprints only.
Can you give more explanation about numbers in your formula: `(duration_in_seconds * 11025 - 4096) / 1365 - 15 - 4 + 1` ?
Is the ending +1 for taking into account rounding?

**Comment by lalinsky** [comment]
The other numbers are from here:

https://github.com/acoustid/chromaprint/blob/master/src/fingerprinter_configuration.cpp

11025 = audio sampling rate
4096 = one FFT window size
1365 = increment of the moving FFT window
15 = number of classifiers - 1
4 = number of coefficients in the chromagram smoothing filter - 1

The last numbers and the +1 might be wrong, since I don't remember the algorithm exactly, but they add up correctly. If you care about the exact numbers, you will have to work them out from the code.
