### ISSUE TITLE
Does Chromaprint detect "similar sounding" music recordings?

### ISSUE THREAD

**Issue by sfsdfd** [acoustid/chromaprint#68]
Please resolve a question about Chromaprint.

A developer has suggested that Chromaprint is capable of comparing a set of song recordings and determining:

(1) That two different recordings are different renditions of the same song, and

(2) That two different recordings of different songs "sound similar" due to acoustic similarities - presumably properties like similar tempo, similar pitch, shared musical features, similar voice / lyrics / instruments, playing technique, etc.

The developer believes that Chromaprint has these capabilities because it incorporates "perceptual hashing," and that Chromaprint "makes some assumptions about content of the audio - that it will be a song, or some tune, etc." The developer wishes to use it to analyze the developer's own recordings over a span of several years to detect "similarities" among the recordings.

Another developer believes that Chromaprint is limited to detecting similar (but non-identical) binary representations of *identical content*, such as would be useful for de-duplication - but that recordings of different songs, or of different renditions of the same song, would generate completely dissimilar fingerprints even though they "sound similar" or are perceived similarly by humans.

Can you please comment?

**Comment by unmade** [comment]
Sorry, I guess I'm kinda responsible for @sfsdfd off toping in your issues.

I indeed wrote a [library](https://github.com/unmade/audiomatch), that compares two fingerprints made by Chromaprint and checks if they are similar. It basically does what described [here](https://groups.google.com/forum/#!msg/acoustid/Uq_ASjaq3bw/kLreyQgxKmgJ) and in that [gist](https://gist.github.com/lalinsky/1132166). Based on the resulted score the libraries makes some assumptions if two records are similar. 

> The developer wishes to use it to analyze the developer's own recordings over a span of several years to detect "similarities" among the recordings.

This statement is incorrect. I actually looking for recording of the the same songs (maybe in different tempo using different recorder) and so on. But the song played is rather the same.

**Comment by sfsdfd** [comment]
To clarify:

"I have hundreds of Voice Memos records of me playing guitar and singing. I decided to find all similar records and see how I've progressed over the years. Listening to them and sorting manually was not an option, so I made this tool."

"if I play on my guitar Stairway too Heaven on the guitar will Shazam tell what song is it? Is it counts for similar audio or not? That's what I needed, but for my own records, that shazam don't have"

Is Chromaprint a suitable tool for this project?

**Comment by TragicWarrior** [comment]
@sfsdfd , Maybe yes, maybe no.  For chromaprint to produce the kind of result you're looking for certain things need to be true.

I used it in an anti-piracy tool.   Let's say you bought "Stairway to Heaven" from 20 different online stores and then you tried to use a cryptographic hash on them (like MD5), you'll get 20 different results.  This is due to things like codec, bit rates, which encoder was used, etc...  This is where chromaprint will do just fine.

However, there is another factor at play here which is similar to your situation.  In my example, LZ may have recorded several different versions of the song... perhaps an unplugged live version, an LP version, etc...  These varied recordings may have some drastic differences... How far into the recording does the music actually start?  Does the artist tell some story before going into the song?  Did they choose a slower or faster tempo that day for some reason.  All of these factors will affect chromaprint.

When I implemented the tool, I would tell it to skip leading silence and start 30 seconds into the track and then do it's thing for about 30 seconds.  Then I took the output and ran it through a simhash algo that I tweaked until I was happy.  The results would go into a database and I would see a massive, but not complete de-duplication.  For example, I saw there were about 80 variants of Britney Spears "Baby One More Time".  After running it through my chromaprint based tool, there were about 12 variants.

So, my original answer... maybe yes, maybe no.  It depends.

Hope that helps.

**Comment by lalinsky** [comment]
The answer is that Chromaprint can be only used for detecting nearly-identical recordings. The same song performed by two different artists, or anything like that, is outside of the scope of the library. Sometimes you get lucky, because the versions are too similar, but it doesn't work in general.
